server.port=8080

spring.messages.basename=messages
spring.mvc.locale-resolver=session
spring.security.enabled=false

# spring.datasource.url=jdbc:mysql://localhost:3306/it_platform?useSSL=false&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Disable default security for now (development only)
spring.security.user.name=admin
spring.security.user.password=admin

# Increase upload size for large Excel files
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# Base Principale (smartitplatform)
spring.datasource.url=jdbc:mysql://localhost:3306/smartitplatform?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Base Secondaire (it_platform)
spring.datasource.itplatform.url=jdbc:mysql://localhost:3306/it_platform?useSSL=false&serverTimezone=UTC
spring.datasource.itplatform.username=root
spring.datasource.itplatform.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true